apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqldb
  labels:
     app: mysqldb
     type: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      type: back-end
  template:
    metadata:
     name: mysqldb-pod
     labels:
        app: mysqldb
        type: back-end
    spec:
      containers:
      - name: mysqldb
        image: prathameshbhujade/mysqldb:1.0
        ports:
          - containerPort: 3306
        envFrom:
          - configMapRef:
                name: db-config
          - secretRef:
                name: db-secret
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      nodeSelector:
        capacity: once

---

apiVersion: v1
kind: Service
metadata:
   name: sqldb-svc
spec:
   ports:
     - port: 3306
   clusterIP: None
   selector:
      app: mysqldb
      type: back-end
